# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    # general
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    # project config
    -   id: check-yaml
    -   id: check-toml
    # code files
    -   id: fix-encoding-pragma
    -   id: check-ast
# python tools
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.990
    hooks:
    -   id: mypy
-   repo: https://github.com/psf/black
    rev:  "22.10.0"
    hooks:
    -   id: black
        language_version: "python3.10.8"
